version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - network
  
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - network

networks:
  network:
    driver: bridge